

 var db = [
				new Business(
				1,
				"royalty-pizza-san-francisco",
				 "Royalty Pizza",
				"http://www.yelp.com/biz/royalty-pizza-san-francisco",
				 "http://s3-media2.fl.yelpcdn.com/bphoto/D-HSxr-OUfBnl4p_p0DYKA/ms.jpg",
				"829 Geary St<br/> San Francisco US  94109  ",
				"http://m.yelp.com/biz/royalty-pizza-san-francisco",
				"http://s3-media3.fl.yelpcdn.com/assets/2/www/img/902abeed0983/ico/stars/v1/stars_small_3.png",
				45,
				37.747999335966,
				-122.6518351868,
				 ["Pizza"],
				  [{name:"$88 for $100","dealUrl":"http://www.yelp.com/deals/royalty-pizza-san-francisco-2"} ])
				,
				new Business(
				2,
				"greenlid-studiomix-san-francisco",
				"GreenLid Studiomix",
				"http://www.yelp.com/biz/greenlid-studiomix-san-francisco",
				 "http://s3-media1.fl.yelpcdn.com/bphoto/5m2iSkqHdFrLffcoEdXesQ/ms.jpg",
				"1000 Van Ness Ave<br/> 3rd Fl<br/>  San Francisco US  94109  ",
				"http://m.yelp.com/biz/greenlid-studiomix-san-francisco",
				"http://s3-media1.fl.yelpcdn.com/assets/2/www/img/c7623205d5cd/ico/stars/v1/stars_small_5.png",
				2,
				37.9847999335966,
				-122.421518351868,
				["Juice Bars & Smoothies", "Coffee & Tea", "Salad"],
				[  {name:"$15 for $30", dealUrl:"http://www.yelp.com/deals/greenlid-studiomix-san-francisco"}]),
new Business(
				3,
				"royalty-pizza-san-francisco",
				 "Royalty Pizza",
				"http://www.yelp.com/biz/royalty-pizza-san-francisco",
				 "http://s3-media2.fl.yelpcdn.com/bphoto/D-HSxr-OUfBnl4p_p0DYKA/ms.jpg",
				"829 Geary St<br/> San Francisco US  94109  ",
				"http://m.yelp.com/biz/royalty-pizza-san-francisco",
				"http://s3-media3.fl.yelpcdn.com/assets/2/www/img/902abeed0983/ico/stars/v1/stars_small_3.png",
				45,
				37.7861099,
				-122.0169922,
				 ["Pizza"],
				  [{name:"$88 for $100","dealUrl":"http://www.yelp.com/deals/royalty-pizza-san-francisco-2"} ])
				  ,
				new Business(
				4,
				"greenlid-studiomix-san-francisco",
				"GreenLid Studiomix",
				"http://www.yelp.com/biz/greenlid-studiomix-san-francisco",
				 "http://s3-media1.fl.yelpcdn.com/bphoto/5m2iSkqHdFrLffcoEdXesQ/ms.jpg",
				"1000 Van Ness Ave<br/> 3rd Fl<br/> San Francisco US  94109  ",
				"http://m.yelp.com/biz/greenlid-studiomix-san-francisco",
				"http://s3-media1.fl.yelpcdn.com/assets/2/www/img/c7623205d5cd/ico/stars/v1/stars_small_5.png",
				2,
				37.7847999335966,
				-122.221518351868,
				["Juice Bars & Smoothies", "Coffee & Tea", "Salad"],
				[  {name:"$15 for $30", dealUrl:"http://www.yelp.com/deals/greenlid-studiomix-san-francisco"}])
				,
				
new Business(
				5,
				"royalty-pizza-san-francisco",
				 "Royalty Pizza",
				"http://www.yelp.com/biz/royalty-pizza-san-francisco",
				 "http://s3-media2.fl.yelpcdn.com/bphoto/D-HSxr-OUfBnl4p_p0DYKA/ms.jpg",
				"829 Geary St<br/>  San Francisco US  94109  ",
				"http://m.yelp.com/biz/royalty-pizza-san-francisco",
				"http://s3-media3.fl.yelpcdn.com/assets/2/www/img/902abeed0983/ico/stars/v1/stars_small_3.png",
				45,
				37.2861099,
					-122.4169922,
				 ["Pizza"],
				[{name:"$88 for $100","dealUrl":"http://www.yelp.com/deals/royalty-pizza-san-francisco-2"} ])
				  ,
				new Business(
				6,
				"greenlid-studiomix-san-francisco",
				"GreenLid Studiomix",
				"http://www.yelp.com/biz/greenlid-studiomix-san-francisco",
				 "http://s3-media1.fl.yelpcdn.com/bphoto/5m2iSkqHdFrLffcoEdXesQ/ms.jpg",
				"1000 Van Ness Ave<br/> 3rd Fl<br/>  San Francisco US  94109  ",
				"http://m.yelp.com/biz/greenlid-studiomix-san-francisco",
				"http://s3-media1.fl.yelpcdn.com/assets/2/www/img/c7623205d5cd/ico/stars/v1/stars_small_5.png",
				2,
				37.7847999335966,
				-122.421518351868,
				["Juice Bars & Smoothies", "Coffee & Tea", "Salad"],
				[  {name:"$15 for $30", dealUrl:"http://www.yelp.com/deals/greenlid-studiomix-san-francisco"}]),
				new Business(
				7,
				"royalty-pizza-san-francisco",
				 "Royalty Pizza",
				"http://www.yelp.com/biz/royalty-pizza-san-francisco",
				 "http://s3-media2.fl.yelpcdn.com/bphoto/D-HSxr-OUfBnl4p_p0DYKA/ms.jpg",
				"829 Geary St<br/>  San Francisco US  94109  ",
				"http://m.yelp.com/biz/royalty-pizza-san-francisco",
				"http://s3-media3.fl.yelpcdn.com/assets/2/www/img/902abeed0983/ico/stars/v1/stars_small_3.png",
				45,
				37.7861099,
					-122.5169922,
				 ["Pizza"],
				  [{name:"$88 for $100","dealUrl":"http://www.yelp.com/deals/royalty-pizza-san-francisco-2"} ])
				  ,
				new Business(
				8,
				"greenlid-studiomix-san-francisco",
				"GreenLid Studiomix",
				"http://www.yelp.com/biz/greenlid-studiomix-san-francisco",
				 "http://s3-media1.fl.yelpcdn.com/bphoto/5m2iSkqHdFrLffcoEdXesQ/ms.jpg",
				"1000 Van Ness Ave<br/> 3rd Fl<br/>  San Francisco US  94109  ",
				"http://m.yelp.com/biz/greenlid-studiomix-san-francisco",
				"http://s3-media1.fl.yelpcdn.com/assets/2/www/img/c7623205d5cd/ico/stars/v1/stars_small_5.png",
				2,
				37.4847999335966,
				-122.421518351868,
				["Juice Bars & Smoothies", "Coffee & Tea", "Salad"],
				[  {name:"$15 for $30", dealUrl:"http://www.yelp.com/deals/greenlid-studiomix-san-francisco"}])
					
			];